changelog:
  categories:
    - title: "🚀 Features"
      labels:
        - "enhancement"
        - "feature"

    - title: "🐛 Bug Fixes"
      labels:
        - "bug"
        - "bugfix"
        - "fix"

    - title: "🔧 Maintenance"
      labels:
        - "maintenance"
        - "refactor"
        - "chore"
        - "docs"
        - "documentation"
        - "Translations"

    - title: "📦 Dependencies"
      labels:
        - "dependencies"
