name: 🛠️ Feature request
description: Suggest an idea for this project
title: "[FEATURE]: "
labels: ["enhancement", "maintainer Check"]
projects:
  - talkarr/2
assignees:
  - CommanderRedYT

body:
  - type: markdown
    attributes:
        value: |
            Thank you for reaching out. Please fill out the form below to help us understand the feature request better.

  - type: textarea
    id: feature-description
    attributes:
        label: Describe the feature
        description: A clear and concise description of what the feature is.
        placeholder: Describe the feature
    validations:
        required: true

  - type: textarea
    id: feature-solution
    attributes:
        label: Describe the solution
        description: A clear and concise description of what you want to happen.
        placeholder: Describe the solution
    validations:
        required: true

  - type: textarea
    id: feature-alternatives
    attributes:
        label: Describe alternatives
        description: A clear and concise description of any alternative solutions or features you've considered.
        placeholder: Describe alternatives
