on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
  issue_comment:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign-project:
    name: Assign issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Assign bugs to the Bugs project
        if: |
          contains(github.event.issue.labels.*.name, 'bug') ||
          contains(github.event.issue.type.name, 'Bug') ||
          contains(github.event.pull_request.labels.*.name, 'bug')
        uses: srggrs/assign-one-project-github-action@1.3.1
        with:
          project: 'https://github.com/orgs/talkarr/projects/1'
          column_name: 'To triage'

      - name: Assign features to the Features project
        if: |
            contains(github.event.issue.labels.*.name, 'feature') ||
            contains(github.event.issue.labels.*.name, 'enhancement') ||
            contains(github.event.issue.type.name, 'Feature') ||
            contains(github.event.pull_request.labels.*.name, 'feature')
        uses: srggrs/assign-one-project-github-action@1.3.1
        with:
          project: 'https://github.com/orgs/talkarr/projects/2'
