name: Manage pull requests
on:
  pull_request_target

permissions: {}

jobs:
  labels:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Label the PR
        uses: actions/labeler@v6
        with:
          sync-labels: 'false'
