name: Manage pull requests
on:
  pull_request_target

permissions: {}

jobs:
  labels:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
    
      - name: Label the PR
        uses: actions/labeler@v6
        with:
          sync-labels: 'false'
          repo-token: ${{ steps.generate-token.outputs.token }}
