# check if the translation submodule has new commits, and if so, create a pull request to update the translations
name: Update Translations
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

env:
  TRANSLATION_PATH: src/translations

permissions: {}

jobs:
  check-and-update-translations:
    name: Check and Update Translations
    runs-on: ubuntu-latest
    # check that the event is not from a branch to automated/update-translations
    if: ${{ ! endsWith(github.ref, vars.TRANSLATION_BRANCH) && ! startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'
          persist-credentials: false

      - name: Fetch complete history for the translation submodule
        run: |
          cd ${TRANSLATION_PATH}
          git fetch --unshallow || true  # Ensure we have the full history

      - name: Check for translation updates
        continue-on-error: true
        run: |
          git submodule update --remote --rebase ${TRANSLATION_PATH}
          git diff --exit-code

      - name: Delete existing translation branch if it exists
        uses: actions/github-script@v7
        with:
          script: |
            const branch = process.env.TRANSLATION_BRANCH;
            const ref = await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `heads/${branch}`
            }).catch(() => null);
            if (ref) {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `heads/${branch}`
              });
              console.log(`Deleted existing branch: ${branch}`);
            } else {
              console.log(`Branch ${branch} does not exist, no need to delete.`);
            }
        env:
          TRANSLATION_BRANCH: ${{ vars.TRANSLATION_BRANCH }}

      - name: Create Pull Request if translations updated
        if: steps.check-for-translation-updates.outcome != 'success'
        uses: peter-evans/create-pull-request@v7
        with:
          title: 'Update translations'
          reviewers: 'CommanderRedYT'
          sign-commits: 'true'
          commit-message: '[automated] Update translations from submodule'
          branch: '${{ vars.TRANSLATION_BRANCH }}'
          body: 'This pull request updates the translations from the submodule. You can find the changes in the [translation repo](https://github.com/talkarr/talkarr-translations)'
          token: ${{ steps.generate-token.outputs.token }}
