# check if the translation submodule has new commits, and if so, create a pull request to update the translations
name: Update Translations
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering
  push:
    paths:
      - .github/workflows/translations.yml

permissions:
  contents: write  # Allows the action to push changes to the repository
  pull-requests: write  # Allows the action to create pull requests

env:
  TRANSLATION_PATH: src/translations

jobs:
  check-and-update-translations:
    name: Check and Update Translations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Fetch complete history for the translation submodule
        run: |
          cd ${TRANSLATION_PATH}
          git fetch --unshallow || true  # Ensure we have the full history

      - name: Check for translation updates
        run: |
          git submodule update --remote --rebase ${TRANSLATION_PATH}
          git diff --exit-code || echo "Translations have been updated."

      - name: Create Pull Request if translations updated
        if: failure()  # Only run if there are changes
        uses: peter-evans/create-pull-request@v7
        with:
          title: 'Update translations'
          reviewers: 'CommanderRedYT'
          sign-commits: 'true'
          commit-message: '[automated] Update translations from submodule'
          branch: 'automated/update-translations'
          body: 'This pull request updates the translations from the submodule. You can find the changes in the [translation repo](https://github.com/talkarr/talkarr-translations)'
